config/routes.rb
Rails.application.routes.draw do
  
  resources :merchant_applications do 
    resource :business_info, except:[:new, :create, :delete]
    resource :owner_info, except:[:new, :create, :delete]
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/merchant_application.rb
class MerchantApplication < ApplicationRecord

  has_one :business_info

  has_many :owner_infos

  after_initialize do |merchant_application|
    self.business_info = self.build_business_info if self.business_info.blank?
    self.owner_infos.build if self.owner_infos.empty?
  end
end

app/controllers/merchant_applications_controller.rb
class MerchantApplicationsController < AuthorizedController
  before_action :set_merchant_application, only: [:show, :edit, :update, :destroy]
  # GET /merchant_applications
  # GET /merchant_applications.json
  def index
    @merchant_applications = MerchantApplication.all
  end

  # GET /merchant_applications/1
  # GET /merchant_applications/1.json
  def show
  end

  # GET /merchant_applications/new
  def new
    @merchant_application = MerchantApplication.new
  end

  # GET /merchant_applications/1/edit
  def edit
  end

  # POST /merchant_applications
  # POST /merchant_applications.json
  def create
    @merchant_application = MerchantApplication.new(merchant_application_params)

    respond_to do |format|
      if @merchant_application.save
        format.html { redirect_to merchant_applications_path, notice: 'Merchant application was successfully created.' }
        format.json { render :show, status: :created, location: @merchant_application }
      else
        format.html { render :new }
        format.json { render json: @merchant_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchant_applications/1
  # PATCH/PUT /merchant_applications/1.json
  def update
    respond_to do |format|
      if @merchant_application.update(merchant_application_params)
        format.html { redirect_to @merchant_application, notice: 'Merchant application was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant_application }
      else
        format.html { render :edit }
        format.json { render json: @merchant_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchant_applications/1
  # DELETE /merchant_applications/1.json
  def destroy
    @merchant_application.destroy
    respond_to do |format|
      format.html { redirect_to merchant_applications_url, notice: 'Merchant application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant_application
      @merchant_application = MerchantApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_application_params
      params.require(:merchant_application).permit(:name)
    end
end

app/helpers/merchant_applications_helper.rb
module MerchantApplicationsHelper
end

app/views/merchant_applications/_form.html.erb
<%= form_with(model: merchant_application, local: true) do |form| %>
  <% if merchant_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(merchant_application.errors.count, "error") %> prohibited this merchant_application from being saved:</h2>

      <ul>
      <% merchant_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :merchant_application_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/merchant_applications/edit.html.erb
<h1>Editing Merchant Application</h1>

<%= render 'form', merchant_application: @merchant_application %>

<%= link_to 'Show', @merchant_application %> |
<%= link_to 'Back', merchant_applications_path %>

app/views/merchant_applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merchant Applications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @merchant_applications.each do |merchant_application| %>
      <tr>
        <td><%= merchant_application.name %></td>
        <td><%= link_to 'Business Info', edit_merchant_application_business_info_path(merchant_application)%></td>
        <td><%= link_to 'Show', merchant_application %></td>
        <td><%= link_to 'Edit', edit_merchant_application_path(merchant_application) %></td>
        <td><%= link_to 'Destroy', merchant_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merchant Application', new_merchant_application_path %>

app/views/merchant_applications/new.html.erb
<h1>New Merchant Application</h1>

<%= render 'form', merchant_application: @merchant_application %>

<%= link_to 'Back', merchant_applications_path %>

app/views/merchant_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @merchant_application.name %>
</p>

<%= link_to 'Edit', edit_merchant_application_path(@merchant_application) %> |
<%= link_to 'Back', merchant_applications_path %>