config/routes.rb
Rails.application.routes.draw do
  
  resources :merchant_applications do 
    resource :business_info, except:[:new, :create, :delete]
    resource :owner_info, except:[:new, :create, :delete]
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/business_info.rb
class BusinessInfo < ApplicationRecord

  belongs_to :merchant_application

  belongs_to :location_address, class_name:"Address"
  accepts_nested_attributes_for :location_address
  
  belongs_to :billing_address, class_name:"Address"
  accepts_nested_attributes_for :billing_address

  after_initialize do |business_info|
    self.location_address = Address.new if self.location_address.blank?
    self.billing_address = Address.new if self.billing_address.blank?
  end
end

app/controllers/business_infos_controller.rb
class BusinessInfosController < ApplicationController
  before_action :set_business_info, only: [:show, :edit, :update]

  # GET /business_infos/1
  # GET /business_infos/1.json
  def show
  end

  # GET /business_infos/1/edit
  def edit
  end


  # PATCH/PUT /business_infos/1
  # PATCH/PUT /business_infos/1.json
  def update
    respond_to do |format|
      if @business_info.update!(business_info_params)
        format.html { redirect_to merchant_applications_path, notice: 'Business info was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_info }
      else
        format.html { render :edit }
        format.json { render json: @business_info.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def merchant_application
      @merchant_application ||= MerchantApplication.find(params[:merchant_application_id])
    end

    def set_business_info
      @business_info = merchant_application.business_info
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_info_params
      params.require(:business_info).permit(:merchant_application_id, :business_info, :business_name, :legal_name, :email, :website, :contact_name, :contact_phone, :contact_fax, :contact_email, :customer_service_email, :retreival_request_to_business_address, :retreival_request_fax_number, :mcc_id, :billing_address_attributes => [:id, :street1, :street2, :city, :state, :zip], :location_address_attributes  => [:id, :street1, :street2, :city, :state, :zip])
    end
end

app/helpers/business_infos_helper.rb
module BusinessInfosHelper
end

app/views/business_infos/_form.html.erb
<%= form_with(model: business_info, url:merchant_application_business_info_path(business_info.merchant_application), local: true) do |form| %>
  <% if business_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business_info.errors.count, "error") %> prohibited this business_info from being saved:</h2>

      <ul>
      <% business_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :business_name %>
    <%= form.text_field :business_name, id: :business_info_business_name %>
  </div>

  <div class="field">
    <%= form.label :legal_name %>
    <%= form.text_field :legal_name, id: :business_info_legal_name %>
  </div>


  <%= form.fields_for :location_address, @business_info.location_address do |location_address_fields| %>
    <div class="field">
      <%= location_address_fields.label :street1, "Location Street1" %>
      <%= location_address_fields.text_field :street1, id: :business_info_location_address_street1 %>
    </div>

    <div class="field">
      <%= location_address_fields.label :street2, "Location Street2" %>
      <%= location_address_fields.text_field :street2, id: :business_info_location_address_street1 %>
    </div>

    <div class="field">
      <%= location_address_fields.label :city, "Location City" %>
      <%= location_address_fields.text_field :city, id: :business_info_location_address_street1 %>
    </div>

    <div class="field">
      <%= location_address_fields.label :state, "Location State" %>
      <%= location_address_fields.text_field :state, id: :business_info_location_address_street1 %>
    </div>

    <div class="field">
      <%= location_address_fields.label :zip, "Location Zip" %>
      <%= location_address_fields.text_field :zip, id: :business_info_location_address_street1 %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :business_info_email %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, id: :business_info_website %>
  </div>

  <%= form.fields_for :billing_address, @business_info.billing_address do |billing_address_fields| %>
    <div class="field">
      <%= billing_address_fields.label :street1, "Billing Street1" %>
      <%= billing_address_fields.text_field :street1, id: :business_info_location_address_street1 %>
    </div>

    <div class="field">
      <%= billing_address_fields.label :street2, "Billing Street2" %>
      <%= billing_address_fields.text_field :street2, id: :business_info_location_address_street1 %>
    </div>

    <div class="field">
      <%= billing_address_fields.label :city, "Billing City" %>
      <%= billing_address_fields.text_field :city, id: :business_info_location_address_street1 %>
    </div>

    <div class="field">
      <%= billing_address_fields.label :state, "Billing State" %>
      <%= billing_address_fields.text_field :state, id: :business_info_location_address_street1 %>
    </div>

    <div class="field">
      <%= billing_address_fields.label :zip, "Billing Zip" %>
      <%= billing_address_fields.text_field :zip, id: :business_info_location_address_street1 %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :contact_name %>
    <%= form.text_field :contact_name, id: :business_info_contact_name %>
  </div>

  <div class="field">
    <%= form.label :contact_phone %>
    <%= form.text_field :contact_phone, id: :business_info_contact_phone %>
  </div>

  <div class="field">
    <%= form.label :contact_fax %>
    <%= form.text_field :contact_fax, id: :business_info_contact_fax %>
  </div>

  <div class="field">
    <%= form.label :contact_email %>
    <%= form.text_field :contact_email, id: :business_info_contact_email %>
  </div>

  <div class="field">
    <%= form.label :customer_service_email %>
    <%= form.text_field :customer_service_email, id: :business_info_customer_service_email %>
  </div>

  <div class="field">
    <%= form.label :retreival_request_to_business_address %>
    <%= form.check_box :retreival_request_to_business_address, id: :business_info_retreival_request_to_business_address %>
  </div>

  <div class="field">
    <%= form.label :retreival_request_fax_number %>
    <%= form.text_field :retreival_request_fax_number, id: :business_info_retreival_request_fax_number %>
  </div>

  <div class="field">
    <%= form.label :mcc_id %>
    <%= form.number_field :mcc_id, id: :business_info_mcc_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/business_infos/edit.html.erb
<h1>Editing Business Info</h1>

<%= render 'form', business_info: @business_info %>

app/views/business_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Business Infos</h1>

<table>
  <thead>
    <tr>
      <th>Merchant application</th>
      <th>Business info</th>
      <th>Business name</th>
      <th>Legal name</th>
      <th>Location address</th>
      <th>Email</th>
      <th>Website</th>
      <th>Billing address</th>
      <th>Contact name</th>
      <th>Contact phone</th>
      <th>Contact fax</th>
      <th>Contact email</th>
      <th>Customer service email</th>
      <th>Retreival request to business address</th>
      <th>Retreival request fax number</th>
      <th>Mcc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_infos.each do |business_info| %>
      <tr>
        <td><%= business_info.merchant_application_id %></td>
        <td><%= business_info.business_info %></td>
        <td><%= business_info.business_name %></td>
        <td><%= business_info.legal_name %></td>
        <td><%= business_info.location_address_id %></td>
        <td><%= business_info.email %></td>
        <td><%= business_info.website %></td>
        <td><%= business_info.billing_address_id %></td>
        <td><%= business_info.contact_name %></td>
        <td><%= business_info.contact_phone %></td>
        <td><%= business_info.contact_fax %></td>
        <td><%= business_info.contact_email %></td>
        <td><%= business_info.customer_service_email %></td>
        <td><%= business_info.retreival_request_to_business_address %></td>
        <td><%= business_info.retreival_request_fax_number %></td>
        <td><%= business_info.mcc_id %></td>
        <td><%= link_to 'Show', business_info %></td>
        <td><%= link_to 'Edit', edit_business_info_path(business_info) %></td>
        <td><%= link_to 'Destroy', business_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business Info', new_business_info_path %>

app/views/business_infos/new.html.erb
<h1>New Business Info</h1>

<%= render 'form', business_info: @business_info %>

<%= link_to 'Back', business_infos_path %>

app/views/business_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Merchant application:</strong>
  <%= @business_info.merchant_application_id %>
</p>

<p>
  <strong>Business info:</strong>
  <%= @business_info.business_info %>
</p>

<p>
  <strong>Business name:</strong>
  <%= @business_info.business_name %>
</p>

<p>
  <strong>Legal name:</strong>
  <%= @business_info.legal_name %>
</p>

<p>
  <strong>Location address:</strong>
  <%= @business_info.location_address_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @business_info.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @business_info.website %>
</p>

<p>
  <strong>Billing address:</strong>
  <%= @business_info.billing_address_id %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @business_info.contact_name %>
</p>

<p>
  <strong>Contact phone:</strong>
  <%= @business_info.contact_phone %>
</p>

<p>
  <strong>Contact fax:</strong>
  <%= @business_info.contact_fax %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @business_info.contact_email %>
</p>

<p>
  <strong>Customer service email:</strong>
  <%= @business_info.customer_service_email %>
</p>

<p>
  <strong>Retreival request to business address:</strong>
  <%= @business_info.retreival_request_to_business_address %>
</p>

<p>
  <strong>Retreival request fax number:</strong>
  <%= @business_info.retreival_request_fax_number %>
</p>

<p>
  <strong>Mcc:</strong>
  <%= @business_info.mcc_id %>
</p>

<%= link_to 'Edit', edit_merchant_application_business_info_path(@merchant_application) %> |
<%= link_to 'Back', merchant_application_path(@merchant_application) %>