config/routes.rb
Rails.application.routes.draw do
  
  resources :merchant_applications do 
    resource :business_info, except:[:new, :create, :delete]
    resource :owner_info, except:[:new, :create, :delete]
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/owner_info.rb
class OwnerInfo < ApplicationRecord
end

app/controllers/owner_infos_controller.rb
class OwnerInfosController < ApplicationController
  before_action :set_owner_info, only: [:show, :edit, :update, :destroy]

  # GET /owner_infos
  # GET /owner_infos.json
  def index
    @owner_infos = OwnerInfo.all
  end

  # GET /owner_infos/1
  # GET /owner_infos/1.json
  def show
  end

  # GET /owner_infos/new
  def new
    @owner_info = OwnerInfo.new
  end

  # GET /owner_infos/1/edit
  def edit
  end

  # POST /owner_infos
  # POST /owner_infos.json
  def create
    @owner_info = OwnerInfo.new(owner_info_params)

    respond_to do |format|
      if @owner_info.save
        format.html { redirect_to @owner_info, notice: 'Owner info was successfully created.' }
        format.json { render :show, status: :created, location: @owner_info }
      else
        format.html { render :new }
        format.json { render json: @owner_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owner_infos/1
  # PATCH/PUT /owner_infos/1.json
  def update
    respond_to do |format|
      if @owner_info.update(owner_info_params)
        format.html { redirect_to @owner_info, notice: 'Owner info was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner_info }
      else
        format.html { render :edit }
        format.json { render json: @owner_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owner_infos/1
  # DELETE /owner_infos/1.json
  def destroy
    @owner_info.destroy
    respond_to do |format|
      format.html { redirect_to owner_infos_url, notice: 'Owner info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner_info
      @owner_info = OwnerInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_info_params
      params.require(:owner_info).permit(:name, :ownership_percent, :date_of_birth, :ssn, :email_address, :home_address_id)
    end
end

app/helpers/owner_infos_helper.rb
module OwnerInfosHelper
end

app/views/owner_infos/_form.html.erb
<div class="col-sm-10 col-md-6">
  <%= form_for @owner info, as: :owner info, url: (@owner info.new_record? ? owner_infos_path(@owner info) : owner_info_path(@owner info)), :html => {class:"form-horizontal"}  do |f| %>
    <% if @owner info.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <div><strong><%= pluralize(@owner info.errors.count, "error") %></strong> prohibited this owner info from being saved:
        </div>

        <ul>
        <% @owner info.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <div class="form-group">
        <%= f.label :name, class:"col-sm-3 control-label" %>
        <div class="col-sm-9">
          <div class=''>
            <%= f.text_field :name, class:"form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :ownership_percent, class:"col-sm-3 control-label" %>
        <div class="col-sm-9">
          <div class=''>
            <%= f.text_field :ownership_percent, class:"form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :date_of_birth, class:"col-sm-3 control-label" %>
        <div class="col-sm-9">
          <div class=''>
            <%= f.text_field :date_of_birth, class:"form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :ssn, class:"col-sm-3 control-label" %>
        <div class="col-sm-9">
          <div class=''>
            <%= f.text_field :ssn, class:"form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email_address, class:"col-sm-3 control-label" %>
        <div class="col-sm-9">
          <div class=''>
            <%= f.text_field :email_address, class:"form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :home_address_id, class:"col-sm-3 control-label" %>
        <div class="col-sm-9">
          <div class=''>
            <%= f.number_field :home_address_id, class:"form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group">
      <div class="col-sm-9 col-sm-offset-3">
        <%= f.submit( class:"btn btn-primary" ) %>
      </div>
    </div>
  <% end %>
</div>

app/views/owner_infos/edit.html.erb
<% content_for :title do %>Editing Owner info<% end %>

<%= render 'form' %>

<%= link_to 'Show', @owner info %> |
<%= link_to 'Back', owner_infos_path %>

app/views/owner_infos/index.html.erb
<% content_for :title do %>Listing Owner infos<% end %>

<% content_for :action_menu_items do %>
  <!-- Do you need to put a helper in /app/helpers/action_menu_helper.rb? -->
  <li><%= link_to 'New Owner info', new_owner_info_path, class:""%></li>
<% end %>
<% content_for :action_menu_back_link do %><% end %>

<%= borg_table id:"owner_infos_table" do %>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Ownership percent</th>
      <th>Date of birth</th>
      <th>Ssn</th>
      <th>Email address</th>
      <th>Home address</th>
    </tr>
  </thead>

  <tbody>
    <% @owner infos.each do |owner info| %>
      <tr>
        <td class="actions">
          <%= link_button_for_show owner info, owner info %>
          <%= link_button_for_edit owner info, edit_owner_info_path(owner info) %>
          <!--<%= link_to 'Destroy', owner_info_path(owner info), method: :delete, data: { confirm: 'Are you sure?' } %>-->
        </td>
        <td><%= owner info.name %></td>
        <td><%= owner info.ownership_percent %></td>
        <td><%= owner info.date_of_birth %></td>
        <td><%= owner info.ssn %></td>
        <td><%= owner info.email_address %></td>
        <td><%= owner info.home_address_id %></td>
      </tr>
    <% end %>
  </tbody>
<% end %>

<br>

app/views/owner_infos/new.html.erb
<% content_for :title do %>New owner info<% end %>

<%= render 'form' %>

app/views/owner_infos/show.html.erb
<% content_for :title do %>Show <%= @owner info %><% end %>
<dl class="dl-horizontal">
  <dt>Name</dt>
  <dd><%= @owner info.name %></dd>
</dl>

<dl class="dl-horizontal">
  <dt>Ownership percent</dt>
  <dd><%= @owner info.ownership_percent %></dd>
</dl>

<dl class="dl-horizontal">
  <dt>Date of birth</dt>
  <dd><%= @owner info.date_of_birth %></dd>
</dl>

<dl class="dl-horizontal">
  <dt>Ssn</dt>
  <dd><%= @owner info.ssn %></dd>
</dl>

<dl class="dl-horizontal">
  <dt>Email address</dt>
  <dd><%= @owner info.email_address %></dd>
</dl>

<dl class="dl-horizontal">
  <dt>Home address</dt>
  <dd><%= @owner info.home_address_id %></dd>
</dl>


<%= link_to 'Edit', edit_owner_info_path(@owner info), class:"btn btn-default" %>
<%= link_to 'Back', owner_infos_path, class:"btn btn-default" %>